name: Build and Test

on:
  push:
    branches: [master]
  pull_request:

permissions:
  contents: read

jobs:
  build-and-test:
    runs-on: macos-latest
    env:
      DEVELOPER_DIR: /Applications/Xcode_26.6.app/Contents/Developer
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - name: Test
        run: >-
          xcodebuild
          -project SomaFM.xcodeproj
          -scheme SomaFM
          -configuration Debug
          -destination 'platform=macOS,arch=arm64'
          CODE_SIGNING_ALLOWED=NO
          test
      - name: Build Universal 2 release
        run: >-
          xcodebuild
          -project SomaFM.xcodeproj
          -scheme SomaFM
          -configuration Release
          -destination 'generic/platform=macOS'
          ARCHS='arm64 x86_64'
          ONLY_ACTIVE_ARCH=NO
          CODE_SIGNING_ALLOWED=NO
          build
